microsoft/go-winio

pipe.go, pipe_test.go, zsyscall.go
@jhowardmsft This breaking change adds CloseWrite() support for pipes that are opened in message mode. This fixes a Docker issue where CloseWrite() is depended upon for closing stdin and part of hijacked connections.
=> Support CloseWrite() by using pipe message mode

reparse.go, wim/decompress.go, wim/lzx/lzx.go, wim/wim.go
This new code supports parsing WIM files. Currently, only WIM files that
were created with no compression or LZX compression are supported. Xpress
compression is not.
=> Add WIM parser

backuptar/tar.go
Switching to using straight binary instead of SDDL in tar headers to avoid failures in converting domain SIDs into/out of SDDL.
Fixes https://github.com/Microsoft/go-winio/issues/19
=> Remove use of SDDL in tar headers

privilege.go
Signed-off-by: John Howard <jhoward@microsoft.com>
@jstarks Adds capability to DisableProcessPrivileges for a process token. Is 0 for disable as found in this sample: https://msdn.microsoft.com/en-us/library/windows/desktop/aa446619(v=vs.85).aspx
=> Add DisableProcessPrivileges

zsyscall_windows.go
Use golang 1.7 mksyscall_windows.go to regenerate zsyscall.go.
/cc @jhowardmsft @jstarks 
=> Regenerate zsyscall with latest mksyscall_windows

file.go, pipe.go, pipe_test.go
Fixes #42 
This adds a `Flush()` method on `win32File`, and calls it on `CloseWrite()` just before sending the 0-length EOF message.
This makes sure that the 0-length message is not collapsed into the previous message, and that functions like io.Copy() do correctly receive an io.EOF error and completes instead of hanging.
The first commit introduces a test that hangs, the second fixes the issue (and makes the test pass)
This was identified, qualified and fixed by @dgageot and me
=> Flush outgoing content before sending EOF message

backup.go, file.go, fileinfo.go, pipe.go, zsyscall_windows.go
fixes #41 
As far as I can tell, this should contain all the runtime.KeepAlive calls needed to conform to the new argument liveness guarantees in Go1.8.x 
It turns out that the main issue was due to passing a Go pointer via native calls to the ioCompletionProcessor, causing the new garbage collection rules to cleanup the struct containing the channel even though it did not have a finalizer.
/cc @jhowardmsft @jstarks PTAL
Thanks @mappu for the initial investigation and repro test.
This also updates zsyscall_windows.go with the new 1.8 go generated code, though it is not related to the KeepAlive, it should be done with the update to 1.8.
=> Added runtime.KeepAlive for the new stricter 1.8 GC

file.go, pipe.go, pipe_test.go
In order to upgrade to go1.8 all IO operations including previous pending IO must have the deadline set when SetReadDeadline or SetWriteDeadline is called.
This moves the timeout cancelation responsibility out of the wait routine and into timers in the deadline code.
@jstarks PTAL
=> Apply read and write deadlines to pending IO

pipe.go, zsyscall_windows.go
fixes #49 
#48 introduced CGO as a dependency when it wasn't really needed (Surprised we didn't already have a CGO dependency tbh). This removes said dependency by delegating the memory management to Windows.
/cc @schmichael @jstarks 
=> Remove cgo as a dependency added by #49

file.go, pipe.go
This fixes a handle leak introduced in #50 
@jstarks 
=> Move f.wg.Done() to Read and Write to avoid leaking handles

pipe.go, zsyscall_windows.go
=> RtlCopyMemory is not available on Nanoserver use builtin copy instead

file.go
This prevent a deadlock if `prepareIo()` is called on a closing file as
`Done()` would never been called afterwards.
Signed-off-by: Kenfe-Mickael Laventure <mickael.laventure@gmail.com>
=> Don't increment the wait count if the file is closing

file.go
The Go race detector doesn't like concurrent access to bool. This change
secures the bool with a mutex.
=> Bool is not atomic

file.go, pipe_test.go
fixes https://github.com/Microsoft/go-winio/issues/29
Go does not allow adding to a sync.WaitGroup that currently has a waiter. This added lock prevents the (rare) case that it happens.
This PR also includes a small test bug fix that was found while working on this issue.
There is no test because the repro conditions are very unreliable, and the test I've been using takes 30s to run (10 times that of the entire current test suite) and only catches it in the race detector at that.
@jstarks
=> Prevent adding to a sync.WaitGroup that has a waiter

file.go, zsyscall_windows.go
Starting in go1.9, Golang lowers the timer frequency when not required reducing CPU usage. The fix to a perf regression in #12 and #13 was a workaround that prevents Golang from doing so. This PR removes the workaround, since the initial issue was fixed. I see no perf regressions in the test suite.
This does not need to be conditional based on Golang verison, as the issue being worked around was only in go1.6, which is no longer supported by go-winio.
Fixes https://github.com/Microsoft/go-winio/issues/69
=> Remove workaround to perf issues in go1.6

file.go, pipe.go, pipe_test.go
Message read mode is the only read mode supported for vSMB named pipes, which are used to provide named pipe mapping for Hyper-V-isolated Windows containers. Transparently support this mode.
=> Support pipe message read mode

file.go, pipe.go
Reference: https://github.com/moby/moby/issues/36562#issuecomment-372347544 
The named pipe in Windows is of message type and the handle to the pipe is in message read mode. Removing the check to allow for Windows named pipes to work.
=> Allow for message pipes in message readmode for Windows named pipes to work.

pipe.go
(I believe this change also should be used instead of PR #75 -- that PR is potentially extraordinarily buggy.)
This changes a few things to try to ensure that we never wind up with
a result of ERROR_FILE_NOT_FOUND, due to a race between closing the
last pipe instance and opening the next.
First we keep an "open" client instance (unused) while the listener
is open, so that we are guaranteed to always have an active pipe
instance.  This means attempts to open while no other instances exist
result in ERROR_PIPE_BUSY instead of ERROR_FILE_NOT_FOUND.
Second we have changed the loop for dialing to eliminate a race condition
that is more or less inherent in WaitNamedPipe when synchronizing with
CreateFile.  The real timeout needs to be some larger value than the
WaitNamedPipe timeout, and …
=> fixes #67 DialPipe problem with multiple calls / waiting for busy pipe

backuptar/tar.go, fileinfo.go
FileAttributes is expected to be 64 bit wide when calling into Windows APIs, no matter the platform. This fix is ensuring that.
=> Update FileAttributes size to work across all platforms

internal/etw/etw.go, internal/etw/eventopt.go, internal/etw/provider.go, internal/etw/zsyscall_windows.go
It turns out ETW only knew to parse our events as TraceLogging previously because they were set to the known TraceLogging channel (11). If you changed the event channel the event was not parsed correctly. This change tells ETW (via EventSetInformation with EventProviderSetTraits) that the provider uses TraceLogging, so events can be parsed even if the channel is changed.
Signed-off-by: Kevin Parsons <kevpar@ntdev.microsoft.com>
=> Set ETW provider info so it's always treated as TraceLogging

vhd/mksyscall_windows.go
Hi, we updated some exported function comments based on best practices from Effective Go. It’s admittedly a relatively minor fix up. Does this help you?
=> Fix function comments based on best practices from Effective Go

vhd/vhd.go, vhd/zvhd.go
Signed-off-by: John Howard <jhoward@microsoft.com>'
@jterry75 Hold fire merging until I've got the end to end validation complete.
This adds `OpenVirtualDisk` to the library. I'm working from the bottom up of this VHD disabling flushing on v2 issue/optimization. In order to send the required IOCTLs, I need a handle to the scratch VHD. Mirrors same functionality in the Windows Orchestrator.
=> Add OpenVirtualDisk to vhd library

pipe.go, pipe_test.go
This adds the DialPipeContext function, providing a way to expire or cancel pending pipe connections using a context.Context.
=> add DialPipeContext

pkg/etw/eventopt.go, pkg/etw/provider.go, pkg/etw/sample/sample.go, pkg/etwlogrus/hook_test.go, pkg/guid/guid.go, pkg/guid/guid_test.go, tools/etw-provider-gen/main.go
We have enough pieces of GUID functionality in different places that it makes sense to provide a common library. A later commit will change hcsshim to use this instead of its internal/guid package.
=> Add guid package

pkg/etw/newprovider.go, pkg/etw/newprovider_unsupported.go, pkg/etw/provider.go
Proper support for ETW on ARM will require additional changes in Go to support
more than 16 bytes of arguments to a syscall callback. Until this work is done,
the ETW package is being changed to no-op on ARM.
=>  Make ETW no-op on ARM

pkg/etw/etw.go, pkg/etw/mksyscall_windows.go, pkg/etw/newprovider.go, pkg/etw/newprovider_unsupported.go, pkg/etw/provider.go, pkg/etw/wrapper_32.go, pkg/etw/wrapper_64.go, pkg/etw/zsyscall_windows.go
The ETW registration handle is defined to be 64-bits on all platforms. The Go
type previously used a uintptr which created problems on 32-bit systems. This
change adds a new wrapper file which receives a 64-bit handle for the functions
defined in it, and correctly passes it to the native ETW functions either as-is
(on 64-bit) or as two 32-bit values (on 32-bit).
This required a minor change in mksyscall_windows.go, to allow multiple syscalls
that map to the same underlying function without causing a duplicate definition
error in the generated file.
=> Fix ETW package to work on 386

pkg/etw/eventdata.go, pkg/etw/fieldopt.go
This change adds support for encoding time.Time values as FILETIME
values in tracelogging events. FILETIME has slightly less precision than
time.Time (100ns vs 1ns), but it is the closest availble match.
=> pkg/etw: Add support for time.Time

file.go
It is convenient to be able to pull off the underlying file handle to pass to other Win32 functions that aren't supported by this library.
This change adds an `Fd() uintptr` method to the file implementation (matches the os.File method of the same name).
=> provide access to underlying file handle

pkg/fs/fs_windows.go
This PR updates the error message in GetFileSystemType to match the function's casing and exports the error. Since I searched for this case-sensitive I ended up not being able to find it earlier; Go lint will complain if we use caps in the `errors.New` at the beginning, so I changed the content slightly.
Open to suggestions for naming/error description.
Signed-off-by: Eric Hotinger <ehotinger@gmail.com>
=> Updates the error message in GetFileSystemType

vhd/vhd.go
When opening a disk for detach mode no parameters are required. This regression
was introduced when the OpenVirtualDisk method was added. Moving the code back
to the previous openVirtualDisk internal method so we can pass nil parameters.
Signed-off-by: Justin Terry (VM) <juterry@microsoft.com>
=> Fix regression in DetachVhd

pipe.go
Created a couple of override methods so that caller has more flexibility on how the pipe is created
=> Expose pipe  access level to caller

go.mod, go.sum
update to pkg/errors v0.9.1 for compatibility with Go 1.13 error (un)wrapping.
=> go.mod: github.com/pkg/errors v0.9.1

vhd/vhd.go, vhd/zvhd.go
This change adds bindings for AttachVirtualDisk and GetVirtualDiskPhysicalPath, some helper functions including
one to create a differencing vhd, exports the create and open parameters, exports the create flags and adds a couple
of missing flags. This will be used mainly to go hand in hand with the new computestorage calls added to hcsshim as all of the
vhd creation and setup needs to be done manually for these calls. microsoft/hcsshim#881.
=> Add new virtdisk calls/refactor vhd package

vhd/vhd.go
* Version 2 didn't exist in RS5 so it's a bit silly to error out in this case.
=> Remove error if ATTACH_VIRTUAL_DISK_PARAMETERS wasn't version 2

pkg/fs/fs_windows.go, pkg/fs/fs_windows_test.go
The [docs](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364993(v=vs.85).aspx) say it returns 0 for failure, non-zero for success.
This implementation is looking for <0 as HRESULT failure, and deriving
an Errno from that.
The new tests fail with GetFileSystemType as it was defined, e.g.,
```
--- FAIL: TestGetFSTypeOfValidButAbsentDrive (0.00s)
fs_windows_test.go:41: GetFileSystemType a:\ unexpectedly succeeded
```
when I definitely do not have an A:\ drive.
=> Correct GetVolumeInformation return type handling

pkg/security/grantvmgroupaccess_test.go
~This is a follow-up to https://github.com/microsoft/go-winio/pull/194, which updates golang.org/x/sys~ merged
On Windows, the os/exec.{Command,CommandContext,LookPath} functions resolve command names that have neither path separators nor file extension (e.g., "git") by first looking in the current working directory before looking in the PATH environment variable.
Go maintainers intended to match cmd.exe's historical behavior.
However, this is pretty much never the intended behavior and as an abundance of precaution this patch prevents that when executing commands.
This patch was prompted by the [Go 1.15.7 security fixes](https://blog.golang.org/path-security).
=> Use golang.org/x/sys/execabs instead of os/exec

pkg/etw/newprovider.go, pkg/etw/newprovider_unsupported.go, pkg/etw/provider.go
We don't support actually using ETW on windows/arm, but to make things
easier for downstream dependencies, we want to still allow the package
to compile and just no-op on this architecture. We do this by returning
a nil Provider, and implementing its methods to no-op when the receiver
is nil.
Previously this was implemented by putting NewProviderWithID in
provider_unsupported.go, but when we refactored the code so that the
actual work was done in NewProviderWithOptions instead, we didn't fix up
provider_unsupported. This change fixes this by putting only
NewProviderWithOptions in provider_unsupported.go, since the other
provider creation functions call into this one.
=> pkg/etw: Fix to build on windows/arm

privilege.go
To support using VHDX for the Docker data root and the writing of image layers an additional privilege is needed.  Added "SeSecurityPrivilege" as an additional option.
Microsoft Case#120082125001494
Signed-off-by: Adam Williams <awilliams@mirantis.com>
=> Add security privilege (needed for VHDX support for docker data root)

.github/workflows/ci.yml, pkg/security/grantvmgroupaccess_test.go
This PR additionally updates the `TestGrantVmGroupAccess` test to account for running on a machine that doesn't have support for running hyper-v VMs, which is the current case for github hosted windows images.
Signed-off-by: Kathryn Baldauf <kabaldau@microsoft.com>
=> Add CI github action for testing on push and PR

.github/workflows/ci.yml
Even though this repo is normally used as a dependency, there are some sample binaries and tools built out of here. This just makes sure they still build after changes 
=> Build the three binaries in this repo from the ci

backuptar/tar.go, fileinfo.go, fileinfo_test.go, zsyscall_windows.go
Reverts microsoft/go-winio#204
This PR adds the changes back originally made in https://github.com/microsoft/go-winio/pull/185. A new release will be made with the minor version number incremented when this PR is merged.
=> Revert removal of "Implement winio.GetFileStandardInfo FileInfo" commits

pkg/security/syscall_windows.go, pkg/security/zsyscall_windows.go, vhd/vhd.go, vhd/zvhd_windows.go
These packages had incorrect error handling for their generated syscall
bindings. The functions they were calling returned errors directly, but
the binding was written such that the generated code was calling
GetLastError instead.
Thankfully, this did not affect the detection of whether or not an error
had occurred, it only caused the value returned in the case of an error
to be not the right error code.
=> Fix syscall error handling in vhd and pkg/security

pkg/etw/provider.go, pkg/etw/wrapper_32.go, pkg/etw/wrapper_64.go
When running on x86, the provider callback doesn't function correctly because two of the arguments are ULONGLONG's (64-bit), which does not align with the uintptr on x86 (32-bit).
This change splits the function into two platform-specific versions to avoid the issue.
=> Fix corruption in x86 callback

README.md
This change updates the README to mention that we now require a valid
DCO on every commit via the bot. Also adds a new contributing section
that houses this info.
This change also re-orders the README into sections:
Contributing, Code of Conduct, Special Thanks
=> Update README with DCO information + re-order into sections

backuptar/tar.go, backuptar/tar_test.go
A recent OS change altered how sparse files are represented in backup
streams. This caused backuptar to no longer work with certain files. The
specific behavior that changed is as follows:
- Empty sparse files (size = 0), previously did not have any data or
sparse block streams in the backup stream. Now, they will have a
data stream with size = 0, and no sparse block streams.
- Sparse files with a single allocated range (e.g. a normal file that
has the sparse attribute set) previously would not show as sparse in
the backup stream. Now, they will show as sparse.
The old backuptar behavior assumed that if the sparse flag was set on
the data stream, then there would always be a set of sparse blocks
following. These changes break this assumption, and so require special
handling.
It is …
=> backuptar: Fix sparse file handling

sd_test.go
TestLookupEmptyNameFails was an identical copy of TestLookupInvalidSid
in the same file. This commit changes the account name queried by the
former to an empty string which is what the name of the test case
suggests.
=> Fix TestLookupEmptyNameFails

go.mod, go.sum, pkg/security/grantvmgroupaccess.go, vhd/vhd.go
Since Go version 1.13, the standard library has built-in support for
wrapping and unwrapping of error values.  This commit bumps the minimum
version required by the module from 1.12 to 1.13, replaces all calls to
errors.Wrap/f with fmt.Errorf and removes the now unneeded dependency on
github.com/pkg/errors.
Signed-off-by: Michael Hofmann <michael.hofmann@bitgestalt.com>
=> Replace github.com/pkg/errors with stdlib errors

vhd/vhd.go, vhd/zvhd_windows.go
While [reworking the vhd package](https://github.com/microsoft/go-winio/commit/e9604c63ae982883093e4d3c33867ce24416af05#diff-e1200af476f67398dde7575bf9966bdccaf140ce444569ff78c485a43f48957a) I'd mistakingly replaced some of the fields
in the OpenVersion2 structure with the incorrect types. They're defined as
Windows BOOLS which is just a type alias for an int, and I'd put their type as
go bools.
As the type is already passed into some functions, to avoid a breaking change just
convert the incorrect type to a new structure with the correct definition internally.
Truthfully this turns out a bit better as supplying a bool makes more sense and is
more go friendly.
=> Fix 'OpenVirtualDiskParameters' BOOL fields

backuptar/tar.go
Separates out Security Descriptor (SDDL), Extended Attribute (EA) and Reparse tag encoding
code into individual functions so that those functions can be reused in other code (like
CimFS layer writing)
Signed-off-by: Amit Barve <ambarve@microsoft.com>
=> functions SDDL, EA & Reparse encoding

backuptar/tar.go
=> backuptar: SecurityDescriptorFromTarHeader() don't decode twice

.github/workflows/ci.yml, fileinfo_test.go, pkg/guid/guid.go, pkg/guid/guid_nonwindows.go, pkg/guid/guid_test.go, pkg/guid/guid_windows.go, reparse.go
#191 added build guard to go-winio, but "pkg/guid" now works on both windows and linux, and is not OS dependent.
This PR is needed to allow using windows-style GUIDs on Linux code that interops with Windows.
Removed build guards from pkg/guid/guid.go.
Build constraints to guid_windows and guid_nonwindows, which redundant with file names, but added for consistency.
Added missing build constraints to other files.
Added Ubuntu to test matrix, along with windows 2022.
=> Updating windows build constraints

.github/workflows/ci.yml, backup.go, backup_test.go, ea_test.go, file.go, fileinfo.go, go.mod, hvsock.go, pipe.go, pipe_test.go, privilege.go, privileges_test.go, sd.go, sd_test.go
1.13 is sufficiently old at this point and net.ErrClosed from 1.16 will be nice
to use.
This change additionally runs go fmt to bring in the new 1.17 build tag syntax
and builds the binaries in our CI with 1.17+.
=> Bump go version to 1.17 in go.mod/CI

.github/workflows/ci.yml, pipe.go
This error used to just be a `errors.New` with the text exactly matching the "use of closed network connection" that you'd get from the Go stdlib. Now that that error was exported as `net.ErrClosed` in Go 1.16 we should
be able to swap to this safely.
=> Assign ErrPipeListenerClosed to net.ErrClosed

pkg/etwlogrus/hook.go, pkg/etwlogrus/opts.go
Added functionality to set the event (task) name and options (such as
event or associated event ID) for ETW events created by the hook based
on the logrus.Entry fields.
This PR supports enhanced logging in the shim.
=> Set ETW event name and options for logrus hook

go.mod, go.sum
Language server complains about
`invalid operation: operator | not defined on windows.TOKEN_ADJUST_PRIVILEGES`
in `privilege.go`. 
Upgrading to new golang.org/x/sys fixes issue.
=> Upgrade golang/sys to fix warning

file.go
This PR removes receiver names from `timeoutError` as they aren't used.
=> chore: removes unneeded receiver in timeoutError

.gitignore, go.mod, go.sum, hvsock_test.go
Added tests for core Hyper-V socket functionality, including testing
CloseRead and CloseWrite, as well as checking addresses are appropriate
and timeouts work.
Requires #239 
=> Added HV Socket tests

.github/workflows/ci.yml, .golangci.yml
Remove some aggressive linters: `godoc`, `goconst`, `misspel`, `nestif`, and `prealloc.
Also remove `stylecheck` since it is subsumed by `revive`, and the later is more configurable.
Allow tests and build stages to continue even if linter fails.
=> Soften linter

.github/workflows/ci.yml, .golangci.yml
Update golanci-lint to 1.50, and remove `structcheck`, which was deprecated in new version.
Additionally, disable `revive`s `unhandled_errors` linter, since currently `errcheck` (a default linter) does the same, and ignores common situations (eg, `io.Close`, `fmt.Print`).
=> Bump linter, remove structcheck, ignore unhandled_errors

pkg/etw/sample/main_windows.go
It looks like for the purpose of the example "a" logger was needed, so not strictly logrus (probably `fmt.Println()` would've worked even).
This patch removes logrus as dependency for the example. The only remaining use of logrus in this repository is now in the pkg/etc/etwlogrus package, which _does_ need logrus, but (possibly) could become its own module if we want to remove logrus as dependency of go-winio itself.
=> pkg/etw/sample: remove dependency on github.com/sirupsen/logrus

tools/mkwinsyscall/mkwinsyscall.go
Add two change lists that were added to `golang.org/x/sys/windows/mkwinsyscall`:
1. [support "." and "-" in DLL name](https://go-review.googlesource.com/c/sys/+/463215)
2. [write source to temp file if formatting fails](https://go-review.googlesource.com/c/sys/+/463216)
=> Apply two upstream CL to mkwinsyscall

pipe.go
In a lab setting of multiple Windows machines, several machines were unable to create a named pipe server:
- Windows Server 2012 R2 build 9600
- Windows 10 Pro build 10240
It is unclear why some of these machines failed, because other machines with the same OS were not affected.
This issue was solved by modifying the ObjectAttributes.Attributes flag being passed to `NtCreateNamedPipeFile`. This change did not impact previously working machines so it appears safe for general use.
**Background:**
Inspecting the output from the system call, ntCreateNamedPipeFile() returned the following:
Retval: 3221225530
Status: -1073741766
There was no named pipe present in the PowerShell output: `Get-ChildItem -Path "\\.\pipe\"`
To rule out machine specific issues, an alternate named pipe server was …
=> Unable to create named pipe on certain WS2012, Win 10 Pro machines

.github/workflows/ci.yml, .golangci.yml, hvsock.go, internal/socket/socket.go, internal/stringbuffer/wstring.go, pipe.go, pkg/etw/eventdescriptor.go, pkg/security/grantvmgroupaccess.go, wim/lzx/lzx.go
Update linter to 1.52, update go used in CI to 1.19
Fix various lint errors, mostly comment spacing
Use gotestsum in CI to pretty up testing logs
Add names to CI steps for prettier UI experience
=> update linter and fix lint errors

.github/workflows/ci.yml, .golangci.yml, backuptar/tar_test.go, file.go, fileinfo_test.go, hvsock_test.go, pipe_test.go, pkg/bindfilter/bind_filter_test.go, pkg/etw/provider_test.go, pkg/guid/guid_test.go, pkg/security/grantvmgroupaccess_test.go
Run fuzzing tests in CI.
Use race detector when running tests.
Add missing `t.Helper()` calls.
Update test helpers in `pkg/bindfilter` to use `RtlGetNtVersionNumbers` instead of reading registry, and skip tests if not running as admin.
=> Update tests; run fuzzing

backup.go, backup_test.go, backuptar/tar.go, ea_test.go, file.go, hvsock.go, hvsock_test.go, internal/fs/fs.go, internal/fs/zsyscall_windows.go, pipe.go, pipe_test.go, pkg/bindfilter/bind_filter.go, pkg/etw/eventdata.go, pkg/etw/fieldopt.go, pkg/security/grantvmgroupaccess.go, pkg/security/syscall_windows.go, pkg/security/zsyscall_windows.go, privilege.go, sd.go, zsyscall_windows.go
Where ever possible, use `golang.org/x/sys/windows` instead of `syscall` (which has been deprecated since go1.11).
Using `windows.LocalFree` requires using `unsafe.Pointer`, which ensures that the Go garbage collector does not try to free memory pre-maturely if it was previously declared as a pointer.
Since `syscall.Handle` is part of API for `vhd` package, it was left unchanged.
For security descriptor functions, switch to using `windows.SECURITY_DESCRIPTOR` to avoid unnecessary byte manipulation and panics due to missing input validation and error checking.
=> Switch from sycall to windows

backuptar/tar.go
`tar.TypeRegA` is deprecated. (We already use the suggested replacement, `tar.TypeReg`.)
https://pkg.go.dev/archive/tar#pkg-constants
=> [lint] Remove deprecated tar.TypeRegA

pipe.go
I would like to use impersonation on the server side of the pipe, but I currently cannot because all pipes are connected using the anonymous impersonation level.
This patch adds a new function that provides the ability to explicitly specify the desired impersonation level.
Fixes #297
=> pipe.go: add DialPipeAccessImpLevel

.github/workflows/ci.yml, hvsock.go, hvsock_go118_test.go, pkg/fs/fs_windows_test.go, pkg/fs/resolve_test.go
Close the socket created in
`github.com/Microsoft/go-winio/pkg/ListenHvsock` if either the `Bind` or `Listen` calls fail.
Go changed `filepath.VolumeName` code, resulting in different behavior in `github.com/Microsoft/go-winio/pkg/fs.GetFileSystemType`. Update test accordingly.
Also add more debug logs to `pkg\fs\resolve_test.go`.
Also, move add skip for fuzzing on WS2019 or older to `FuzzHvSockRxTx` code directly, instead of in ci.yml.
See: https://go-review.googlesource.com/c/go/+/540277
=> Bug: Close hvsock handle on listen error; fix tests

pkg/security/grantvmgroupaccess_test.go
- relates to https://github.com/microsoft/go-winio/pull/195
This reverts commit f2a56450f4feb316514aa0f5978a989fe6b1a328, which switched from os/exec to the golang.org/x/sys/execabs package to mitigate security issues (mainly on Windows) with lookups resolving to binaries in the current directory.
from the go1.19 release notes https://go.dev/doc/go1.19#os-exec-path
> ## PATH lookups
>
> Command and LookPath no longer allow results from a PATH search to be found
> relative to the current directory. This removes a common source of security
> problems but may also break existing programs that depend on using, say,
> exec.Command("prog") to run a binary named prog (or, on Windows, prog.exe) in
> the current directory. See the os/exec package documentation for information
> about how best to …
=> switch back from golang.org/x/sys/execabs to os/exec (go1.19)

backuptar/tar.go, fileinfo.go, fileinfo_test.go, pkg/fs/fs_windows_test.go, zsyscall_windows.go
Cherry picks https://github.com/microsoft/go-winio/commit/8f0d50b3b381b741820d6737cfbda5b9284be616 , https://github.com/microsoft/go-winio/commit/008bc6ea439f15884bef0b52f2772190c382bf46
=> [release/0.4] Cherry pick fixes from main branch

fileinfo.go, fileinfo_test.go, pkg/fs/fs_windows_test.go
* fileinfo: internally fix FileBasicInfo memory alignment
* Update test with review feedback
Remove unused winName.
Extract more into Windows alignment consts to repeat less.
Document reason for having multiple alignment consts for the same value.
---------
(cherry picked from commit 008bc6ea439f15884bef0b52f2772190c382bf46)
=> [release/0.5] fileinfo: internally fix FileBasicInfo memory alignment (#312)
