microsoft/go-winio

sd.go

Fix build on windows/386

---

file.go
zsyscall.go

Fixes performance regression in GO 1.6

---

file.go
zsyscall.go

Oops, capitalization error on last PR. This fixes it @jstarks 

Fixed error in #12

---

privilege.go
zsyscall.go

Also optimize privilege setting with the same privilege name multiple
times.

Add function for setting privileges globally

---

wim/lzx/lzx.go

replace pointless(?) modulo function

Replace unnecessary mod17 function with builtin mod

---

backuptar/tar.go

Signed-off-by: John Howard <jhoward@microsoft.com>
@swernli @jstarks

Fix filename length check alt data stream

---

pipe.go

Copy pointer to prevent data race on pipe connection

---

backup.go
backuptar/tar.go
backuptar/tar_test.go
ea.go
ea_test.go

@darrenstahlmsft @benhillis PTAL

Add support for EAs to Windows tars

---

pipe.go
pipe_test.go

This change resolves the issue where Accept() returns ERROR_NO_DATA
because the client closes the connection immediately. It resolves
the race by ignoring that particular connection and waiting on a
new one.

pipe: Resolve race between close and connect

---

sd_test.go

Signed-off-by: John Stephens <johnstep@docker.com>

Call Fatalf to use the format specifier

---

pkg/etwlogrus/hook.go

ETW and Logrus have similar, but different definitiosn of log level.
Originally, the plan was to just convert the integer value of the Logrus level
to an ETW level, and leave it at that. However, it turns out there are tools
that assume you are logging with the standard set of ETW log level. So now we
will map the Logrus level to an ETW level, so that these tools better.

Map Logrus level to standard ETW level

---

pkg/security/grantvmgroupaccess.go
pkg/security/grantvmgroupaccess_test.go
pkg/security/mksyscall_windows.go
pkg/security/syscall_windows.go
pkg/security/zsyscall_windows.go

Signed-off-by: John Howard <jhoward@microsoft.com>
@jterry75 @jstarks PTAL.

Add GrantVmGroupAccess

---

pkg/security/grantvmgroupaccess.go
pkg/security/grantvmgroupaccess_test.go

Signed-off-by: John Howard <jhoward@microsoft.com>
@jterry75 Here you go. Removes the capability SID. Updates the VMGroup SID. Makes read-only. Fixes tests for directory in the new mode, even though I know you don't care about that....

Fix GrantVmGroupAccess

---

pkg/etw/fieldopt.go
pkg/etw/sample/sample.go
pkg/etwlogrus/hook.go

This is so we can use the smart logging functionality from hcsshim.

Move smart ETW field logging to base etw library

---

pkg/etwlogrus/hook.go

This change updates the logrus hook to sort the incoming logrus data
before passing it to the tracelogging code. This is useful because it
ensures that two instances of the same event have the fields in the same
order, which is necessary to get WPA to line the fields up.

pkg/etwlogrus: Ensure stable event field order

---

go.mod
go.sum

Transition to Go modules

---

pkg/etwlogrus/hook.go

etwlogrus: Fix event logging not including fields

---

pkg/etwlogrus/HookTest.wprp
pkg/etwlogrus/hook_test.go

etwlogrus: Improve tests to actually go through logrus hook

---

pkg/etwlogrus/hook.go

etwlogrus: Ignore error from ETW WriteEvent

---

pkg/guid/guid.go
pkg/guid/guid_test.go

pkg/guid: Prefer passing GUID by value

---

hvsock.go
pkg/etw/eventopt.go
pkg/etw/newprovider.go
pkg/etw/newprovider_unsupported.go
pkg/etw/provider.go
pkg/etw/sample/sample.go

Fix errors introduced with guid-by-value change

---

pkg/guid/guid.go
pkg/guid/guid_test.go

Several improvements to the guid package. See the list of commits for individual descriptions.

pkg/guid: Various improvements

---

pkg/etwlogrus/hook.go

Replace ETW Logrus hook levels with AllLevels

---

pkg/etwlogrus/hook.go

etwlogrus: Pass through entry time as ETW field

---

pkg/fs/fs_windows.go

@jterry75 as discussed in https://github.com/containerd/containerd/issues/3362
cc @kevpar 
Signed-off-by: Eric Hotinger <ehotinger@gmail.com>

Adds a file system helper file for determining the file system type.

---

file.go

Fix interface-wrapped nil returned by MakeOpenFile

---

pkg/etw/provider.go
pkg/etw/provider_test.go
pkg/guid/guid.go
pkg/guid/guid_test.go

- Improved tests
- Better handling of GUID variant and version
- V5 GUID support
- Improved ETW provider name to GUID code, and added a test for it

guid package improvements

---

pkg/etw/newprovider.go
pkg/etw/provider.go
pkg/etw/sample/sample.go

Adding the ability for a caller of the ETW library to specify a provider group for their ETW provider.

Add ability to set provider group

---

CODEOWNERS

Signed-off-by: Kathryn Baldauf <kabaldau@microsoft.com>

Add codeowners file so containerplat is auto added as reviewers

---

.gitignore

Add .vscode folder and go workspaces to git ignore

---

wim/decompress.go
wim/wim.go

Allow to build WIM module for linux. I've looked at the code and I don't see any Windows OS specific bits, it also compiles and works just fine for linux.

Allow to build WIM module for linux

---

.github/workflows/ci.yml

add version number to fix linting issues

---

.github/dependabot.yml

Create an explicit `dependabot.yml` file to manage dependabot update PRs

enable dependency updates
